/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: main.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "main.pb-c.h"
void   app__ip_port__init
                     (App__IpPort         *message)
{
  static const App__IpPort init_value = APP__IP_PORT__INIT;
  *message = init_value;
}
size_t app__ip_port__get_packed_size
                     (const App__IpPort *message)
{
  assert(message->base.descriptor == &app__ip_port__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t app__ip_port__pack
                     (const App__IpPort *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &app__ip_port__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t app__ip_port__pack_to_buffer
                     (const App__IpPort *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &app__ip_port__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
App__IpPort *
       app__ip_port__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (App__IpPort *)
     protobuf_c_message_unpack (&app__ip_port__descriptor,
                                allocator, len, data);
}
void   app__ip_port__free_unpacked
                     (App__IpPort *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &app__ip_port__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   app__connection__init
                     (App__Connection         *message)
{
  static const App__Connection init_value = APP__CONNECTION__INIT;
  *message = init_value;
}
size_t app__connection__get_packed_size
                     (const App__Connection *message)
{
  assert(message->base.descriptor == &app__connection__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t app__connection__pack
                     (const App__Connection *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &app__connection__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t app__connection__pack_to_buffer
                     (const App__Connection *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &app__connection__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
App__Connection *
       app__connection__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (App__Connection *)
     protobuf_c_message_unpack (&app__connection__descriptor,
                                allocator, len, data);
}
void   app__connection__free_unpacked
                     (App__Connection *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &app__connection__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor app__ip_port__field_descriptors[2] =
{
  {
    "ip",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(App__IpPort, ip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "port",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(App__IpPort, port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned app__ip_port__field_indices_by_name[] = {
  0,   /* field[0] = ip */
  1,   /* field[1] = port */
};
static const ProtobufCIntRange app__ip_port__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor app__ip_port__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "app.IpPort",
  "IpPort",
  "App__IpPort",
  "app",
  sizeof(App__IpPort),
  2,
  app__ip_port__field_descriptors,
  app__ip_port__field_indices_by_name,
  1,  app__ip_port__number_ranges,
  (ProtobufCMessageInit) app__ip_port__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor app__connection__field_descriptors[5] =
{
  {
    "src",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(App__Connection, src),
    &app__ip_port__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dst",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(App__Connection, dst),
    &app__ip_port__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timest",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(App__Connection, timest),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "app_ids",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(App__Connection, n_app_ids),
    offsetof(App__Connection, app_ids),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "protocol",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(App__Connection, protocol),
    &app__protocol__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned app__connection__field_indices_by_name[] = {
  3,   /* field[3] = app_ids */
  1,   /* field[1] = dst */
  4,   /* field[4] = protocol */
  0,   /* field[0] = src */
  2,   /* field[2] = timest */
};
static const ProtobufCIntRange app__connection__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor app__connection__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "app.Connection",
  "Connection",
  "App__Connection",
  "app",
  sizeof(App__Connection),
  5,
  app__connection__field_descriptors,
  app__connection__field_indices_by_name,
  1,  app__connection__number_ranges,
  (ProtobufCMessageInit) app__connection__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue app__protocol__enum_values_by_number[3] =
{
  { "OTHER", "APP__PROTOCOL__OTHER", 0 },
  { "TCP", "APP__PROTOCOL__TCP", 6 },
  { "UDP", "APP__PROTOCOL__UDP", 17 },
};
static const ProtobufCIntRange app__protocol__value_ranges[] = {
{0, 0},{6, 1},{17, 2},{0, 3}
};
static const ProtobufCEnumValueIndex app__protocol__enum_values_by_name[3] =
{
  { "OTHER", 0 },
  { "TCP", 1 },
  { "UDP", 2 },
};
const ProtobufCEnumDescriptor app__protocol__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "app.Protocol",
  "Protocol",
  "App__Protocol",
  "app",
  3,
  app__protocol__enum_values_by_number,
  3,
  app__protocol__enum_values_by_name,
  3,
  app__protocol__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
