/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: dns.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "dns.pb-c.h"
void   app__dns_query__init
                     (App__DnsQuery         *message)
{
  static const App__DnsQuery init_value = APP__DNS_QUERY__INIT;
  *message = init_value;
}
size_t app__dns_query__get_packed_size
                     (const App__DnsQuery *message)
{
  assert(message->base.descriptor == &app__dns_query__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t app__dns_query__pack
                     (const App__DnsQuery *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &app__dns_query__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t app__dns_query__pack_to_buffer
                     (const App__DnsQuery *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &app__dns_query__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
App__DnsQuery *
       app__dns_query__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (App__DnsQuery *)
     protobuf_c_message_unpack (&app__dns_query__descriptor,
                                allocator, len, data);
}
void   app__dns_query__free_unpacked
                     (App__DnsQuery *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &app__dns_query__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   app__dns_rr_type_adata__init
                     (App__DnsRrTypeAData         *message)
{
  static const App__DnsRrTypeAData init_value = APP__DNS_RR_TYPE_ADATA__INIT;
  *message = init_value;
}
size_t app__dns_rr_type_adata__get_packed_size
                     (const App__DnsRrTypeAData *message)
{
  assert(message->base.descriptor == &app__dns_rr_type_adata__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t app__dns_rr_type_adata__pack
                     (const App__DnsRrTypeAData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &app__dns_rr_type_adata__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t app__dns_rr_type_adata__pack_to_buffer
                     (const App__DnsRrTypeAData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &app__dns_rr_type_adata__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
App__DnsRrTypeAData *
       app__dns_rr_type_adata__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (App__DnsRrTypeAData *)
     protobuf_c_message_unpack (&app__dns_rr_type_adata__descriptor,
                                allocator, len, data);
}
void   app__dns_rr_type_adata__free_unpacked
                     (App__DnsRrTypeAData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &app__dns_rr_type_adata__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   app__dns_rr_type_aaaadata__init
                     (App__DnsRrTypeAAAAData         *message)
{
  static const App__DnsRrTypeAAAAData init_value = APP__DNS_RR_TYPE_AAAADATA__INIT;
  *message = init_value;
}
size_t app__dns_rr_type_aaaadata__get_packed_size
                     (const App__DnsRrTypeAAAAData *message)
{
  assert(message->base.descriptor == &app__dns_rr_type_aaaadata__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t app__dns_rr_type_aaaadata__pack
                     (const App__DnsRrTypeAAAAData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &app__dns_rr_type_aaaadata__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t app__dns_rr_type_aaaadata__pack_to_buffer
                     (const App__DnsRrTypeAAAAData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &app__dns_rr_type_aaaadata__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
App__DnsRrTypeAAAAData *
       app__dns_rr_type_aaaadata__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (App__DnsRrTypeAAAAData *)
     protobuf_c_message_unpack (&app__dns_rr_type_aaaadata__descriptor,
                                allocator, len, data);
}
void   app__dns_rr_type_aaaadata__free_unpacked
                     (App__DnsRrTypeAAAAData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &app__dns_rr_type_aaaadata__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   app__dns_rr_type_mx_data__init
                     (App__DnsRrTypeMxData         *message)
{
  static const App__DnsRrTypeMxData init_value = APP__DNS_RR_TYPE_MX_DATA__INIT;
  *message = init_value;
}
size_t app__dns_rr_type_mx_data__get_packed_size
                     (const App__DnsRrTypeMxData *message)
{
  assert(message->base.descriptor == &app__dns_rr_type_mx_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t app__dns_rr_type_mx_data__pack
                     (const App__DnsRrTypeMxData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &app__dns_rr_type_mx_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t app__dns_rr_type_mx_data__pack_to_buffer
                     (const App__DnsRrTypeMxData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &app__dns_rr_type_mx_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
App__DnsRrTypeMxData *
       app__dns_rr_type_mx_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (App__DnsRrTypeMxData *)
     protobuf_c_message_unpack (&app__dns_rr_type_mx_data__descriptor,
                                allocator, len, data);
}
void   app__dns_rr_type_mx_data__free_unpacked
                     (App__DnsRrTypeMxData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &app__dns_rr_type_mx_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   app__dns_rr_type_ns_data__init
                     (App__DnsRrTypeNsData         *message)
{
  static const App__DnsRrTypeNsData init_value = APP__DNS_RR_TYPE_NS_DATA__INIT;
  *message = init_value;
}
size_t app__dns_rr_type_ns_data__get_packed_size
                     (const App__DnsRrTypeNsData *message)
{
  assert(message->base.descriptor == &app__dns_rr_type_ns_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t app__dns_rr_type_ns_data__pack
                     (const App__DnsRrTypeNsData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &app__dns_rr_type_ns_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t app__dns_rr_type_ns_data__pack_to_buffer
                     (const App__DnsRrTypeNsData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &app__dns_rr_type_ns_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
App__DnsRrTypeNsData *
       app__dns_rr_type_ns_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (App__DnsRrTypeNsData *)
     protobuf_c_message_unpack (&app__dns_rr_type_ns_data__descriptor,
                                allocator, len, data);
}
void   app__dns_rr_type_ns_data__free_unpacked
                     (App__DnsRrTypeNsData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &app__dns_rr_type_ns_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   app__dns_rr_type_ptr_data__init
                     (App__DnsRrTypePtrData         *message)
{
  static const App__DnsRrTypePtrData init_value = APP__DNS_RR_TYPE_PTR_DATA__INIT;
  *message = init_value;
}
size_t app__dns_rr_type_ptr_data__get_packed_size
                     (const App__DnsRrTypePtrData *message)
{
  assert(message->base.descriptor == &app__dns_rr_type_ptr_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t app__dns_rr_type_ptr_data__pack
                     (const App__DnsRrTypePtrData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &app__dns_rr_type_ptr_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t app__dns_rr_type_ptr_data__pack_to_buffer
                     (const App__DnsRrTypePtrData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &app__dns_rr_type_ptr_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
App__DnsRrTypePtrData *
       app__dns_rr_type_ptr_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (App__DnsRrTypePtrData *)
     protobuf_c_message_unpack (&app__dns_rr_type_ptr_data__descriptor,
                                allocator, len, data);
}
void   app__dns_rr_type_ptr_data__free_unpacked
                     (App__DnsRrTypePtrData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &app__dns_rr_type_ptr_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   app__dns_rr__init
                     (App__DnsRr         *message)
{
  static const App__DnsRr init_value = APP__DNS_RR__INIT;
  *message = init_value;
}
size_t app__dns_rr__get_packed_size
                     (const App__DnsRr *message)
{
  assert(message->base.descriptor == &app__dns_rr__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t app__dns_rr__pack
                     (const App__DnsRr *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &app__dns_rr__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t app__dns_rr__pack_to_buffer
                     (const App__DnsRr *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &app__dns_rr__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
App__DnsRr *
       app__dns_rr__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (App__DnsRr *)
     protobuf_c_message_unpack (&app__dns_rr__descriptor,
                                allocator, len, data);
}
void   app__dns_rr__free_unpacked
                     (App__DnsRr *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &app__dns_rr__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   app__dns__init
                     (App__DNS         *message)
{
  static const App__DNS init_value = APP__DNS__INIT;
  *message = init_value;
}
size_t app__dns__get_packed_size
                     (const App__DNS *message)
{
  assert(message->base.descriptor == &app__dns__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t app__dns__pack
                     (const App__DNS *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &app__dns__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t app__dns__pack_to_buffer
                     (const App__DNS *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &app__dns__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
App__DNS *
       app__dns__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (App__DNS *)
     protobuf_c_message_unpack (&app__dns__descriptor,
                                allocator, len, data);
}
void   app__dns__free_unpacked
                     (App__DNS *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &app__dns__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor app__dns_query__field_descriptors[3] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(App__DnsQuery, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(App__DnsQuery, type),
    &app__dns_rr_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "class",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(App__DnsQuery, class_),
    &app__dns_class__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned app__dns_query__field_indices_by_name[] = {
  2,   /* field[2] = class */
  0,   /* field[0] = name */
  1,   /* field[1] = type */
};
static const ProtobufCIntRange app__dns_query__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor app__dns_query__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "app.DnsQuery",
  "DnsQuery",
  "App__DnsQuery",
  "app",
  sizeof(App__DnsQuery),
  3,
  app__dns_query__field_descriptors,
  app__dns_query__field_indices_by_name,
  1,  app__dns_query__number_ranges,
  (ProtobufCMessageInit) app__dns_query__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor app__dns_rr_type_adata__field_descriptors[1] =
{
  {
    "address",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(App__DnsRrTypeAData, address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned app__dns_rr_type_adata__field_indices_by_name[] = {
  0,   /* field[0] = address */
};
static const ProtobufCIntRange app__dns_rr_type_adata__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor app__dns_rr_type_adata__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "app.DnsRrTypeAData",
  "DnsRrTypeAData",
  "App__DnsRrTypeAData",
  "app",
  sizeof(App__DnsRrTypeAData),
  1,
  app__dns_rr_type_adata__field_descriptors,
  app__dns_rr_type_adata__field_indices_by_name,
  1,  app__dns_rr_type_adata__number_ranges,
  (ProtobufCMessageInit) app__dns_rr_type_adata__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor app__dns_rr_type_aaaadata__field_descriptors[1] =
{
  {
    "address",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(App__DnsRrTypeAAAAData, address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned app__dns_rr_type_aaaadata__field_indices_by_name[] = {
  0,   /* field[0] = address */
};
static const ProtobufCIntRange app__dns_rr_type_aaaadata__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor app__dns_rr_type_aaaadata__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "app.DnsRrTypeAAAAData",
  "DnsRrTypeAAAAData",
  "App__DnsRrTypeAAAAData",
  "app",
  sizeof(App__DnsRrTypeAAAAData),
  1,
  app__dns_rr_type_aaaadata__field_descriptors,
  app__dns_rr_type_aaaadata__field_indices_by_name,
  1,  app__dns_rr_type_aaaadata__number_ranges,
  (ProtobufCMessageInit) app__dns_rr_type_aaaadata__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor app__dns_rr_type_mx_data__field_descriptors[2] =
{
  {
    "preference",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(App__DnsRrTypeMxData, preference),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mail_exchange",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(App__DnsRrTypeMxData, mail_exchange),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned app__dns_rr_type_mx_data__field_indices_by_name[] = {
  1,   /* field[1] = mail_exchange */
  0,   /* field[0] = preference */
};
static const ProtobufCIntRange app__dns_rr_type_mx_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor app__dns_rr_type_mx_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "app.DnsRrTypeMxData",
  "DnsRrTypeMxData",
  "App__DnsRrTypeMxData",
  "app",
  sizeof(App__DnsRrTypeMxData),
  2,
  app__dns_rr_type_mx_data__field_descriptors,
  app__dns_rr_type_mx_data__field_indices_by_name,
  1,  app__dns_rr_type_mx_data__number_ranges,
  (ProtobufCMessageInit) app__dns_rr_type_mx_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor app__dns_rr_type_ns_data__field_descriptors[1] =
{
  {
    "name_server",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(App__DnsRrTypeNsData, name_server),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned app__dns_rr_type_ns_data__field_indices_by_name[] = {
  0,   /* field[0] = name_server */
};
static const ProtobufCIntRange app__dns_rr_type_ns_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor app__dns_rr_type_ns_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "app.DnsRrTypeNsData",
  "DnsRrTypeNsData",
  "App__DnsRrTypeNsData",
  "app",
  sizeof(App__DnsRrTypeNsData),
  1,
  app__dns_rr_type_ns_data__field_descriptors,
  app__dns_rr_type_ns_data__field_indices_by_name,
  1,  app__dns_rr_type_ns_data__number_ranges,
  (ProtobufCMessageInit) app__dns_rr_type_ns_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor app__dns_rr_type_ptr_data__field_descriptors[1] =
{
  {
    "domain_name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(App__DnsRrTypePtrData, domain_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned app__dns_rr_type_ptr_data__field_indices_by_name[] = {
  0,   /* field[0] = domain_name */
};
static const ProtobufCIntRange app__dns_rr_type_ptr_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor app__dns_rr_type_ptr_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "app.DnsRrTypePtrData",
  "DnsRrTypePtrData",
  "App__DnsRrTypePtrData",
  "app",
  sizeof(App__DnsRrTypePtrData),
  1,
  app__dns_rr_type_ptr_data__field_descriptors,
  app__dns_rr_type_ptr_data__field_indices_by_name,
  1,  app__dns_rr_type_ptr_data__number_ranges,
  (ProtobufCMessageInit) app__dns_rr_type_ptr_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor app__dns_rr__field_descriptors[10] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(App__DnsRr, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(App__DnsRr, type),
    &app__dns_rr_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "class",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(App__DnsRr, class_),
    &app__dns_class__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ttl",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(App__DnsRr, ttl),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rdlength",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(App__DnsRr, rdlength),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "a_data",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(App__DnsRr, rr_data_case),
    offsetof(App__DnsRr, a_data),
    &app__dns_rr_type_adata__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "aaaa_data",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(App__DnsRr, rr_data_case),
    offsetof(App__DnsRr, aaaa_data),
    &app__dns_rr_type_aaaadata__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mx_data",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(App__DnsRr, rr_data_case),
    offsetof(App__DnsRr, mx_data),
    &app__dns_rr_type_mx_data__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ns_data",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(App__DnsRr, rr_data_case),
    offsetof(App__DnsRr, ns_data),
    &app__dns_rr_type_ns_data__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ptr_data",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(App__DnsRr, rr_data_case),
    offsetof(App__DnsRr, ptr_data),
    &app__dns_rr_type_ptr_data__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned app__dns_rr__field_indices_by_name[] = {
  5,   /* field[5] = a_data */
  6,   /* field[6] = aaaa_data */
  2,   /* field[2] = class */
  7,   /* field[7] = mx_data */
  0,   /* field[0] = name */
  8,   /* field[8] = ns_data */
  9,   /* field[9] = ptr_data */
  4,   /* field[4] = rdlength */
  3,   /* field[3] = ttl */
  1,   /* field[1] = type */
};
static const ProtobufCIntRange app__dns_rr__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor app__dns_rr__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "app.DnsRr",
  "DnsRr",
  "App__DnsRr",
  "app",
  sizeof(App__DnsRr),
  10,
  app__dns_rr__field_descriptors,
  app__dns_rr__field_indices_by_name,
  1,  app__dns_rr__number_ranges,
  (ProtobufCMessageInit) app__dns_rr__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor app__dns__field_descriptors[4] =
{
  {
    "connection",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(App__DNS, connection),
    &app__connection__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mssg_type",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(App__DNS, mssg_type),
    &app__dns_mssg_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "questions",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(App__DNS, n_questions),
    offsetof(App__DNS, questions),
    &app__dns_query__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rrs",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(App__DNS, n_rrs),
    offsetof(App__DNS, rrs),
    &app__dns_rr__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned app__dns__field_indices_by_name[] = {
  0,   /* field[0] = connection */
  1,   /* field[1] = mssg_type */
  2,   /* field[2] = questions */
  3,   /* field[3] = rrs */
};
static const ProtobufCIntRange app__dns__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor app__dns__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "app.DNS",
  "DNS",
  "App__DNS",
  "app",
  sizeof(App__DNS),
  4,
  app__dns__field_descriptors,
  app__dns__field_indices_by_name,
  1,  app__dns__number_ranges,
  (ProtobufCMessageInit) app__dns__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue app__dns_mssg_type__enum_values_by_number[3] =
{
  { "DNS_MESSA_UNKNOWN", "APP__DNS_MSSG_TYPE__DNS_MESSA_UNKNOWN", 0 },
  { "DNS_QUERY", "APP__DNS_MSSG_TYPE__DNS_QUERY", 1 },
  { "DNS_RESPONSE", "APP__DNS_MSSG_TYPE__DNS_RESPONSE", 2 },
};
static const ProtobufCIntRange app__dns_mssg_type__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex app__dns_mssg_type__enum_values_by_name[3] =
{
  { "DNS_MESSA_UNKNOWN", 0 },
  { "DNS_QUERY", 1 },
  { "DNS_RESPONSE", 2 },
};
const ProtobufCEnumDescriptor app__dns_mssg_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "app.DnsMssgType",
  "DnsMssgType",
  "App__DnsMssgType",
  "app",
  3,
  app__dns_mssg_type__enum_values_by_number,
  3,
  app__dns_mssg_type__enum_values_by_name,
  1,
  app__dns_mssg_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue app__dns_rr_type__enum_values_by_number[6] =
{
  { "DNS_RR_UNKNOWN", "APP__DNS_RR_TYPE__DNS_RR_UNKNOWN", 0 },
  { "DNS_RR_A", "APP__DNS_RR_TYPE__DNS_RR_A", 1 },
  { "DNS_RR_AAAA", "APP__DNS_RR_TYPE__DNS_RR_AAAA", 2 },
  { "DNS_RR_MX", "APP__DNS_RR_TYPE__DNS_RR_MX", 3 },
  { "DNS_RR_NS", "APP__DNS_RR_TYPE__DNS_RR_NS", 4 },
  { "DNS_RR_PTR", "APP__DNS_RR_TYPE__DNS_RR_PTR", 5 },
};
static const ProtobufCIntRange app__dns_rr_type__value_ranges[] = {
{0, 0},{0, 6}
};
static const ProtobufCEnumValueIndex app__dns_rr_type__enum_values_by_name[6] =
{
  { "DNS_RR_A", 1 },
  { "DNS_RR_AAAA", 2 },
  { "DNS_RR_MX", 3 },
  { "DNS_RR_NS", 4 },
  { "DNS_RR_PTR", 5 },
  { "DNS_RR_UNKNOWN", 0 },
};
const ProtobufCEnumDescriptor app__dns_rr_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "app.DnsRrType",
  "DnsRrType",
  "App__DnsRrType",
  "app",
  6,
  app__dns_rr_type__enum_values_by_number,
  6,
  app__dns_rr_type__enum_values_by_name,
  1,
  app__dns_rr_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue app__dns_class__enum_values_by_number[4] =
{
  { "DNS_CLASS_UNKNOWN", "APP__DNS_CLASS__DNS_CLASS_UNKNOWN", 0 },
  { "DNS_CLASS_IN", "APP__DNS_CLASS__DNS_CLASS_IN", 1 },
  { "DNS_CLASS_NONE", "APP__DNS_CLASS__DNS_CLASS_NONE", 2 },
  { "DNS_CLASS_ANY", "APP__DNS_CLASS__DNS_CLASS_ANY", 3 },
};
static const ProtobufCIntRange app__dns_class__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex app__dns_class__enum_values_by_name[4] =
{
  { "DNS_CLASS_ANY", 3 },
  { "DNS_CLASS_IN", 1 },
  { "DNS_CLASS_NONE", 2 },
  { "DNS_CLASS_UNKNOWN", 0 },
};
const ProtobufCEnumDescriptor app__dns_class__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "app.DnsClass",
  "DnsClass",
  "App__DnsClass",
  "app",
  4,
  app__dns_class__enum_values_by_number,
  4,
  app__dns_class__enum_values_by_name,
  1,
  app__dns_class__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
