version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  schema-registry:
    image: confluentinc/cp-schema-registry:7.3.0
    depends_on:
      - zookeeper
      - kafka
    ports: 
      - 8081:8081
    container_name: schema-registry
    environment: 
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'PLAINTEXT://kafka:29092'

  c-producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: kafka:9092
    volumes:
      - ./producer:/usr/src/app
    command: ["./producer"] 

  python-consumer:
    image: python:3.9
    depends_on:
      - kafka
    working_dir: /usr/src/app
    volumes:
      - ./consumer:/usr/src/app
    command: ["python", "consumer.py"]
