# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: main.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='main.proto',
  package='app',
  syntax='proto3',
  serialized_options=b'\n\010protobufB\006shared',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nmain.proto\x12\x03\x61pp\"\"\n\x06IpPort\x12\n\n\x02ip\x18\x01 \x01(\x0c\x12\x0c\n\x04port\x18\x02 \x01(\r\"\x82\x01\n\nConnection\x12\x18\n\x03src\x18\x01 \x01(\x0b\x32\x0b.app.IpPort\x12\x18\n\x03\x64st\x18\x02 \x01(\x0b\x32\x0b.app.IpPort\x12\x0e\n\x06timest\x18\x03 \x01(\x04\x12\x0f\n\x07\x61pp_ids\x18\x04 \x03(\r\x12\x1f\n\x08protocol\x18\x05 \x01(\x0e\x32\r.app.Protocol*\'\n\x08Protocol\x12\t\n\x05OTHER\x10\x00\x12\x07\n\x03TCP\x10\x06\x12\x07\n\x03UDP\x10\x11\x42\x12\n\x08protobufB\x06sharedb\x06proto3'
)

_PROTOCOL = _descriptor.EnumDescriptor(
  name='Protocol',
  full_name='app.Protocol',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OTHER', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TCP', index=1, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UDP', index=2, number=17,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=188,
  serialized_end=227,
)
_sym_db.RegisterEnumDescriptor(_PROTOCOL)

Protocol = enum_type_wrapper.EnumTypeWrapper(_PROTOCOL)
OTHER = 0
TCP = 6
UDP = 17



_IPPORT = _descriptor.Descriptor(
  name='IpPort',
  full_name='app.IpPort',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip', full_name='app.IpPort.ip', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='port', full_name='app.IpPort.port', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=53,
)


_CONNECTION = _descriptor.Descriptor(
  name='Connection',
  full_name='app.Connection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='src', full_name='app.Connection.src', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dst', full_name='app.Connection.dst', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timest', full_name='app.Connection.timest', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='app_ids', full_name='app.Connection.app_ids', index=3,
      number=4, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='protocol', full_name='app.Connection.protocol', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=186,
)

_CONNECTION.fields_by_name['src'].message_type = _IPPORT
_CONNECTION.fields_by_name['dst'].message_type = _IPPORT
_CONNECTION.fields_by_name['protocol'].enum_type = _PROTOCOL
DESCRIPTOR.message_types_by_name['IpPort'] = _IPPORT
DESCRIPTOR.message_types_by_name['Connection'] = _CONNECTION
DESCRIPTOR.enum_types_by_name['Protocol'] = _PROTOCOL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IpPort = _reflection.GeneratedProtocolMessageType('IpPort', (_message.Message,), {
  'DESCRIPTOR' : _IPPORT,
  '__module__' : 'main_pb2'
  # @@protoc_insertion_point(class_scope:app.IpPort)
  })
_sym_db.RegisterMessage(IpPort)

Connection = _reflection.GeneratedProtocolMessageType('Connection', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTION,
  '__module__' : 'main_pb2'
  # @@protoc_insertion_point(class_scope:app.Connection)
  })
_sym_db.RegisterMessage(Connection)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
